# config file version
apiVersion: 1

deleteDatasources:
  - name: Lighthouse
    orgId: 1

datasources:
  - name: Lighthouse
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    basicAuth: true
    basicAuthUser: admin
    editable: true
    jsonData:
      version: Flux
      organization: VTEX
      defaultBucket: lighthouse
      httpMode: POST
    secureJsonData:
      basicAuthPassword: admin123
      token: toad@Y#uSK62WU0LG6I^$z

