version: "3"
services:
    # DATABASE
    influxdb:
        image: "influxdb:latest"
        container_name: influxdb
        ports:
            - 8086:8086
        volumes:
            - influxdb_data:/var/lib/influxdb
        environment:
            - DOCKER_INFLUXDB_INIT_MODE=setup
            - DOCKER_INFLUXDB_INIT_USERNAME=admin
            - DOCKER_INFLUXDB_INIT_PASSWORD=admin123
            - DOCKER_INFLUXDB_INIT_ORG=VTEX
            - DOCKER_INFLUXDB_INIT_BUCKET=lighthouse
            - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=toad@Y#uSK62WU0LG6I^$z

    # DASHBOARD
    grafana:
        image: "grafana/grafana-enterprise:latest"
        ports:
            - 80:3000
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=secret
            - GF_PANELS_DISABLE_SANITIZE_HTML=true
        volumes:
            - "./packages/grafana/volume:/var/lib/grafana"
            - "./packages/grafana/provisioning:/etc/grafana/provisioning"
            - "./packages/grafana/grafana.ini:/etc/grafana/grafana.ini"
        depends_on:
            - influxdb

volumes:
    influxdb_data:

    # lighthouse
    # webperf-dashboard-lighthouse:
    #   image: "felicegeracitano/webperf-dashboard-lighthouse:1.1.1"
    #   ports:
    #     - 3000:3000
    #   environment:
    #     - HOST=influxdb
    #   volumes:
    #     - ./config.json:/usr/src/webperf-dashboard-lighthouse/config.json
    #   depends_on:
    #     - influxdb
