version: "3"
services:
    # DATABASE
    influxdb:
        image: "influxdb:latest"
        container_name: influxdb
        ports:
            - 8086:8086
        volumes:
            - influxdb_data:/var/lib/influxdb
        environment:
            - INFLUXDB_DB=grafana
            - INFLUXDB_USER=grafana
            - INFLUXDB_USER_PASSWORD=password
            - INFLUXDB_ADMIN_ENABLED=true
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=password
        restart: always

    kapacitor:
      container_name: kapacitor
      image: kapacitor
      environment:
          KAPACITOR_HOSTNAME: kapacitor
          KAPACITOR_INFLUXDB_0_URLS_0: http://influxdb:8086
      links:
          - influxdb
      ports:
          - "9092:9092"
      depends_on:
            - influxdb

    chronograf:
        container_name: chronograf
        image: "chronograf:latest"
        environment:
            INFLUXDB_URL: http://influxdb:8086
            KAPACITOR_URL: http://kapacitor:9092
        ports:
            - 8888:8888
        links:
            - influxdb
            - kapacitor
        depends_on:
            - influxdb
            - kapacitor

volumes:
    influxdb_data:

    # DASHBOARD
    # grafana:
    #   image: grafana/grafana
    #   ports:
    #     - 80:3000
    #   environment:
    #     - GF_SECURITY_ADMIN_PASSWORD=secret
    #     - GF_PANELS_DISABLE_SANITIZE_HTML=true
    #   volumes:
    #     - "./packages/grafana/volume:/var/lib/grafana"
    #     - "./packages/grafana/provisioning:/etc/grafana/provisioning"
    #     - "./packages/grafana/grafana.ini:/etc/grafana/grafana.ini"
    #   depends_on:
    #     - influxdb

    # lighthouse
    # webperf-dashboard-lighthouse:
    #   image: "felicegeracitano/webperf-dashboard-lighthouse:1.1.1"
    #   ports:
    #     - 3000:3000
    #   environment:
    #     - HOST=influxdb
    #   volumes:
    #     - ./config.json:/usr/src/webperf-dashboard-lighthouse/config.json
    #   depends_on:
    #     - influxdb
