{
 "title": "Monitoring",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "url", "label": "URL", "query": "http://www.exito.com/" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Performance score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"lighthouse\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"performance-score\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"performance-score\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\r\n  |> filter(fn: (r) => r[\"url\"] == \"${url}\")"
    }
   ]
  },
  {
   "title": "Best practice score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"lighthouse\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"best-practices-score\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"best-practices-score\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\r\n  |> filter(fn: (r) => r[\"url\"] == \"${url}\")"
    }
   ]
  },
  {
   "title": "Accessibility Score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"lighthouse\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"accessibility-score\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"accessibility-score\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\r\n  |> filter(fn: (r) => r[\"url\"] == \"${url}\")"
    }
   ]
  },
  {
   "title": "SEO score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"lighthouse\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"seo-score\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"seo-score\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\r\n  |> filter(fn: (r) => r[\"url\"] == \"${url}\")"
    }
   ]
  },
  {
   "title": "PWA score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"lighthouse\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"pwa-score\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"pwa-score\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\r\n  |> filter(fn: (r) => r[\"url\"] == \"${url}\")"
    }
   ]
  },
  {
   "title": "Performance Metrics (Lower is better)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "First Contentful Paint (FCP)",
   "type": "timeseries",
   "description": "First Contentful Paint marks the time at which the first text or image is painted.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"lighthouse\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"first-contentful-paint-score\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"first-contentful-paint-score\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\r\n  |> filter(fn: (r) => r[\"url\"] == \"${url}\")"
    }
   ]
  },
  {
   "title": "First Meaningful Paint",
   "type": "timeseries",
   "description": "First Meaningful Paint measures when the primary content of a page is visible.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"lighthouse\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"first-meaningful-paint-score\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"first-meaningful-paint-score\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\r\n  |> filter(fn: (r) => r[\"url\"] == \"${url}\")"
    }
   ]
  },
  {
   "title": "Speed Index",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "query": "from(bucket: \"lighthouse\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"speed-index-score\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"speed-index-score\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\r\n  |> filter(fn: (r) => r[\"url\"] == \"${url}\")"
    }
   ]
  },
  {
   "title": "Time to Interactive",
   "type": "timeseries",
   "description": "Interactive marks the time at which the page is fully interactive.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "query": "from(bucket: \"lighthouse\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"interactive-score\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"interactive-score\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\r\n  |> filter(fn: (r) => r[\"url\"] == \"${url}\")"
    }
   ]
  },
  { "title": "Other", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "DOM nodes count score",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"lighthouse\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dom-size-score\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dom-size-score\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\r\n  |> filter(fn: (r) => r[\"url\"] == \"${url}\")"
    }
   ]
  },
  {
   "title": "DOM max nodes depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"lighthouse\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dom-max-depth\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dom-max-depth\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\r\n  |> filter(fn: (r) => r[\"url\"] == \"${url}\")"
    }
   ]
  },
  {
   "title": "DOM Max child nodes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "query": "from(bucket: \"lighthouse\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"dom-max-child-elements\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"dom-max-child-elements\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\r\n  |> filter(fn: (r) => r[\"url\"] == \"${url}\")"
    }
   ]
  },
  {
   "title": "Total Bytes Downloaded",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "query": "from(bucket: \"lighthouse\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"total-byte-weight-score\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"total-byte-weight-score\")\r\n  |> filter(fn: (r) => r[\"host\"] == \"host1\")\r\n  |> filter(fn: (r) => r[\"url\"] == \"${url}\")"
    }
   ]
  },
  { "title": "Network Requests", "type": "timeseries", "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 } }
 ]
}